### ISSUE TITLE
Support running azure devops  

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/gitops-promotion#20]
Support running Squash merge types in main gitops branch.

![image](https://user-images.githubusercontent.com/14774899/115357987-81974f00-a1bd-11eb-9690-a590a12a0ad0.png)

When running in this mode we get: 
```
/bin/bash --noprofile --norc /agent/_work/_temp/67837ee4-5b06-4d65-b127-989a2ba1426a.sh 
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb590ea] 
 
goroutine 1 [running]: 
github.com/xenitab/gitops-promotion/pkg/git.(*AzdoGITProvider).GetPRThatCausedCommit(0xc000140bd0, 0xde4db8, 0xc00042b400, 0xc000182a20, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 
 /workspace/pkg/git/azdo.go:243 +0x30a 
github.com/xenitab/gitops-promotion/pkg/git.(*Repository).GetPRThatCausedCurrentCommit(0xc000140c00, 0xde4db8, 0xc00042b400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 
 /workspace/pkg/git/repository.go:198 +0x133 
github.com/xenitab/gitops-promotion/pkg/command.PromoteCommand(0xde4db8, 0xc00042b400, 0xc0004816a0, 0x20, 0x7fffc71f5b18, 0x45c, 0x22, 0xc000440120, 0xce72e0, 0xc00008c101) 
 /workspace/pkg/command/command.go:60 +0x316 
main.main() 
 /workspace/main.go:56 +0x9bc 
##[error]Bash exited with code '2'. 
```

**Comment by simongottschlag** [comment]
https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/branch_policy_merge_types

**Comment by NissesSenap** [comment]
Simon this is not a terraform config that is needed. 
We need to support it in our golang code.

**Comment by simongottschlag** [comment]
Resolved by https://github.com/XenitAB/gitops-promotion/pull/29
